### ISSUE TITLE
Programmatically get data

### ISSUE THREAD

**Issue by AdaShoelace** [MustafaSalih1993/rsblocks#16]
**Issue**  
Currently rsblocks spawns subprocesses by `Command::new("...")` in several places. This approach presumes the user have the called utility installed on their system. Eg `xsetroot`. This can also lead to zombie processes which is less than ideal.

**Suggested solution**  
Retrieve the data programmatically by utilizing the system APIs.  
Update the gui via an X11 library eg. [breadx](https://github.com/not-a-seagull/breadx).

I have started to implement the suggested solution and hope to have a pull request ready in the coming days.  
I made this issue mostly to make you aware about both the problem and that I am working on it.

**Comment by MustafaSalih1993** [comment]
Thanks for this @AdaShoelace, it will be nice, i will assign this to you  👍🏾
