### ISSUE TITLE
Restructure/refactor

### ISSUE THREAD

**Issue by AdaShoelace** [MustafaSalih1993/rsblocks#32]
**Issue**
Having the entire project reside in one file is bad for a myriad of reasons, encapsulation, readability etc. Also is the project intended to be used as a library AND a binary?

**Solution**  
Restructure the project into neatly organized modules.
If applicable, delete `lib.rs` after restructuring of the project.

**Comment by MustafaSalih1993** [comment]
thanks for this, this is a MUST, moving arround in the code now became really annoying too, already added this to the TODO list

**Comment by MustafaSalih1993** [comment]
@AdaShoelace consider looking at the new structure of the project

**Comment by AdaShoelace** [comment]
Hmm, this is a tad unfortunate. I'm at almost finished with my refactoring of the project and really don't like to do it all again tbh.

**Comment by MustafaSalih1993** [comment]
Ok, and thank you really appreciated bro
