### ISSUE TITLE
Failed to parse config

### ISSUE THREAD

**Issue by AngelBerihuete** [MustafaSalih1993/rsblocks#47]
Dear MustafaSalih. I've followed the steps you indicate to install rsblocks, but when I execute rsblocks in st terminal this is shown:

```bash
~ (base) rsblocks
thread 'main' panicked at 'Failed to parse config: Message("duplicate field `netspeed`", Some(Pos { marker: Marker { index: 151, line: 4, col: 9 }, path: "." }))', src/config/mod.rs:47:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Any clue to resolve it? ... maybe is because I've got activated systray?

**Comment by MustafaSalih1993** [comment]
hello AngelBerihuete 

i have read this error message
`duplicate field 'netspeed'`
it looks like your rsblocks configuration file have 2 fields of 'netspeed' please double check your config file
