### ISSUE TITLE
Battery issue?

### ISSUE THREAD

**Issue by salehmuhamed** [MustafaSalih1993/rsblocks#48]
My battery name is BAT0 as I edited in the config file, but I'm still getting "check your battery source name"!

**Comment by salehmuhamed** [comment]
Just fixed it :D, the issue was with file `battery.rs`, it calls `charge_..._....` from my system, in my distribution the file name is more like this formula: `energy_..._...`, I edited it and it works very well right now, thanks dude for this very nice bar :D

**Comment by MustafaSalih1993** [comment]
salehmu 
thanks for reporting, I'll try to get the battery percentage and status programmatically without reading a file, on my free time from work :D
