### ISSUE TITLE
Char limit for spotify.rs

### ISSUE THREAD

**Issue by salehmu** [MustafaSalih1993/rsblocks#53]
If spotify tack name is long, it will hide rest of all blocks, image explains.
![image](https://user-images.githubusercontent.com/74098495/117509238-2ec5e180-af8a-11eb-9d87-4451f90690c5.png)
**Suggested solution** 
May adding chars limit would solve it.

**Comment by MustafaSalih1993** [comment]
salehmu 
thanks for reporting and your nice suggestion, i will add that on the next PR
